language: python
python:
  - "3.7"
before_install:
  - sudo apt install build-essential python3-dev python3-pippython3-gst-1.0 gir1.2-gstreamer-1.0 gir1.2-gst-plugins-base-1.0 gstreamer1.0-plugins-good gstreamer1.0-plugins-ugly gstreamer1.0-tools
install:
  - pip install .
script:
  - pytest